# Generated by Django 4.2.1 on 2023-06-13 15:53
from sqlite3 import IntegrityError

import requests
from django.db import migrations, transaction


def get_city_departments(app, *args):
    try:
        with transaction.atomic():
            CityDepartment = app.get_model('financiationAPI', 'CityDepartment')
            URL = 'https://apis.datos.gob.ar/georef/api/departamentos?provincia=córdoba&campos=nombre&max=50'
            r = requests.get(URL)
            data = r.json()
            departamentos = []
            for d in data.get('departamentos'):
                departamento = CityDepartment(id=d.get("id"), name=d.get("nombre"), description=d.get("nombre"))
                departamentos.append(departamento)
            CityDepartment.objects.bulk_create(departamentos)
    except IntegrityError:
        print("--------------ERROR--------------")


def get_localities(app, *args):
    try:
        with transaction.atomic():
            Locality = app.get_model('financiationAPI', 'Locality')
            URL = "https://apis.datos.gob.ar/georef/api/localidades?provincia=Córdoba&campos=nombre,departamento&max=1000"
            r = requests.get(URL)
            data = r.json()
            localidades = []
            for d in data.get("localidades"):
                localidad = Locality(name=d.get("nombre"), id_department_id=d.get("departamento").get("id"))
                localidades.append(localidad)
            Locality.objects.bulk_create(localidades)
    except IntegrityError:
        print("--------------ERROR--------------")


class Migration(migrations.Migration):
    dependencies = [
        ('financiationAPI', '0002_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.RunPython(get_city_departments),
        migrations.RunPython(get_localities)
    ]
